# Generated by Django 2.1.8 on 2019-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0006_auto_20190109_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageannotation",
            name="highlight",
            field=models.TextField(blank=True),
        ),
    ]
