# Generated by Django 2.1.9 on 2019-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0007_pageannotation_highlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
