# Generated by Django 4.0.7 on 2022-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0026_auto_20220920_1828"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectiondirectory",
            name="level",
        ),
        migrations.RemoveField(
            model_name="collectiondirectory",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="collectiondirectory",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="collectiondirectory",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="collectiondirectory",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="collectiondirectory",
            name="depth",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="collectiondirectory",
            name="numchild",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="collectiondirectory",
            name="path",
            field=models.CharField(unique=True, max_length=255, editable=False),
        ),
    ]
