# Generated by Django 4.2.4 on 2023-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filingcabinet", "0028_alter_collectiondirectory_depth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
