# Generated by Django 4.2.16 on 2025-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0029_alter_document_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectiondirectory",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown is supported"),
        )
    ]
