# Generated by Django 5.2.1 on 2025-06-25 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0030_collectiondirectory_description'),
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondirectory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collectiondocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', through='filingcabinet.CollectionDocument', through_fields=('collection', 'document'), to=settings.FILINGCABINET_DOCUMENT_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentportal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pageannotation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggeddocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
