# Generated by Django 5.2.10 on 2026-04-15 11:11

import filingcabinet.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0031_alter_collectiondirectory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=filingcabinet.language.get_language_choices, default=filingcabinet.language.get_default_language, max_length=10),
        ),
    ]
