# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
        ('filingcabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='filingcabinet_documentcollection', to=settings.FILINGCABINET_DOCUMENT_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'FILINGCABINET_DOCUMENTCOLLECTION_MODEL',
            },
        ),
    ]
