# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0003_auto_20180810_1559'),
    ]

    operations = [
    ]
