# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0004_auto_20180810_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10),
        ),
    ]
