# Generated by Django 2.1.9 on 2019-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0008_auto_20190806_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
