# Generated by Django 2.1.9 on 2019-08-15 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
        ("filingcabinet", "0010_auto_20190815_1047"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("document", "number")},
        ),
    ]
