# Generated by Django 2.1.9 on 2019-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0011_auto_20190815_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="corrected",
            field=models.BooleanField(default=False),
        ),
    ]
