# Generated by Django 2.2.4 on 2019-10-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filingcabinet', '0012_page_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filingcabinet_documentcollection', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
