# Generated by Django 2.2.4 on 2019-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filingcabinet', '0013_auto_20191001_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiondocument',
            options={'ordering': ['order', 'document__title']},
        ),
        migrations.AlterModelOptions(
            name='documentcollection',
            options={'verbose_name': 'document collection', 'verbose_name_plural': 'document collections'},
        ),
        migrations.AddField(
            model_name='collectiondocument',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
