# Generated by Django 2.2.4 on 2019-10-30 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0014_auto_20191007_1827"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="allow_annotation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pageannotation",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
