# Generated by Django 4.0.7 on 2022-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filingcabinet", "0024_alter_collectiondirectory_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectiondirectory",
            name="depth",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectiondirectory",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collectiondirectory",
            name="path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
